"""AWS_REPORT.md generation.

Deterministic on purpose: no wall-clock timestamp, so the report can be diffed
against a golden copy (guide section 29.2). File mtime carries freshness.
"""

from __future__ import annotations

import networkx as nx

# Things a v0.1 estimate does not include. Shown in every report (guide section 18.3).
EXCLUSIONS = (
    "public IPv4 addresses",
    "data transfer that is not explicitly modeled",
    "snapshots and backup beyond included storage",
    "taxes",
    "credits",
    "Savings Plans / Reserved Instances / Spot",
    "free tier",
)

DISCLAIMER = (
    "This is an estimate based only on the modeled resources, the local pricing "
    "catalog, and the usage assumptions stored in the design file. It is not an AWS bill."
)


def _money(amount: str, currency: str) -> str:
    return f"{amount} {currency}"


def generate(graph: nx.MultiDiGraph, analysis: dict, source: str | None = None) -> str:
    meta = graph.graph
    summary = analysis["summary"]
    currency = summary["currency"]
    lines: list[str] = []

    lines += [
        "# AWSGraph Report",
        "",
        "## Summary",
        "",
        f"- Architecture: {meta.get('architecture_name', 'unknown')}",
        f"- Region: {meta.get('region', 'unknown')}",
        f"- Currency: {currency}",
        f"- Catalog: {meta.get('catalog_id', 'unknown')}",
        f"- Schema: {meta.get('schema_version', 'unknown')}",
        f"- Generated by: AWSGraph {meta.get('product_version', 'unknown')}",
        f"- Resources: {summary['node_count']}",
        f"- Relationships: {summary['edge_count']}",
        "",
        "## Estimated Monthly Cost",
        "",
        f"**{_money(summary['monthly_cost'], currency)}**",
        "",
        DISCLAIMER,
        "",
    ]

    lines += ["## Cost Breakdown by Service", "", "| Service | Monthly |", "|---|---|"]
    for service, amount in analysis["cost_by_service"].items():
        lines.append(f"| {service} | {_money(amount, currency)} |")
    lines.append("")

    lines += ["## Architecture Overview", "", "| Resource | Type | Monthly | Status |", "|---|---|---|---|"]
    for _, attrs in sorted(graph.nodes(data=True), key=lambda kv: kv[1]["label"]):
        lines.append(
            f"| {attrs['label']} | {attrs['resource_type']} | "
            f"{_money(attrs.get('monthly_cost', '0'), currency)} | "
            f"{attrs.get('cost_status', 'unknown')} |"
        )
    lines.append("")

    lines += ["## Topology", ""]
    if graph.number_of_edges() == 0:
        lines.append("_No relationships defined._")
    else:
        for source_id, target_id, attrs in graph.edges(data=True):
            source_label = graph.nodes[source_id]["label"]
            target_label = graph.nodes[target_id]["label"]
            lines.append(f"- {source_label} --{attrs['relation']}--> {target_label}")
    lines.append("")

    lines += ["## Unpriced Resources", ""]
    if not analysis["unpriced"]:
        lines.append("_Every resource was priced._")
    else:
        for item in analysis["unpriced"]:
            reasons = "; ".join(item["missing"]) or "no reason recorded"
            lines.append(f"- {item['label']} ({item['service']}): {reasons}")
    lines.append("")

    lines += ["## Assumptions and Exclusions", ""]
    assumptions = [
        f"- {attrs['label']}: {assumption}"
        for _, attrs in graph.nodes(data=True)
        for assumption in attrs.get("cost_assumptions", [])
    ]
    if assumptions:
        lines += ["Assumptions used:", "", *assumptions, ""]
    lines += ["Not modeled in v0.1:", ""]
    lines += [f"- {item}" for item in EXCLUSIONS]
    lines.append("")

    lines += ["## Graph Freshness", ""]
    lines.append(f"- Source design: {source or 'unknown'}")
    lines.append(f"- Pricing catalog: {meta.get('catalog_id', 'unknown')}")
    lines.append("")

    return "\n".join(lines)
